name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t brayanumba/my-app .
        
      # Testear la imagen Docker (opcional, si tienes tests)
      - name: Run 
        run: |
          docker run -d -p 3000:3000 my-app
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar kubectl para interactuar con Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # Desplegar usando ArgoCD
      - name: Deploy to Kubernetes using ArgoCD
        run: |
          kubectl apply -f k8s/pod.yaml
          argocd app sync my-app --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}
