name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker pull brayanumba/my-app:latest

      # Testear la imagen Docker
      - name: Run 
        run: |
          docker run -d -p 3000:3000 brayanumba/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar dependencias necesarias para Minikube
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl conntrack

      # Instalar crictl
      - name: Install crictl
        run: |
          VERSION="v1.31.0"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-$VERSION-linux-amd64.tar.gz
          rm crictl-$VERSION-linux-amd64.tar.gz

      # Instalar Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=none

      # Configurar kubectl
      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl cluster-info

      # Verificar estado de Minikube
      - name: Verify Minikube
        run: |
          minikube status
          kubectl get nodes

      # Instalar ArgoCD CLI
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      # Configurar ArgoCD
      - name: Configure ArgoCD
        run: |
          kubectl create namespace argocd || true
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd

      # Desplegar aplicación con kubectl
      - name: Deploy application with kubectl
        run: |
          kubectl apply -f k8s/app.yaml
          kubectl get all -n default
